---
repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.14
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--no-cache]
