name: Create release PR

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: telicent-oss/shared-workflows/.github/workflows/python-create-release-pr.yml@main
